/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const createError: typeof import('h3').createError
  const defineCachedEventHandler: typeof import('nitropack').defineCachedEventHandler
  const getQuery: typeof import('h3').getQuery
  const getRouterParam: typeof import('h3').getRouterParam
}
