services:
  nuxt-app:
    build: .
    container_name: nuxt_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tudexgames
    volumes:
      - db_data:/var/lib/mysql
      - ./tudexgames.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_data:
  db_data:
